name: CI
on:
  pull_request:
  push: { branches: [ main ] }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python scripts/pipeline.py
      - name: Check outputs
        run: |
          test -f data/platform_rankings.json
          test -f data/github_trends.json
          test -f data/news.json
          test -f data/ai_note.json
